### ISSUE TITLE
Urgent! Data Group feature does not work 

### ISSUE THREAD

**Issue by Naigege** [energy-data/energydata.info#229]
After entering the Group info - MTF Survey (in the metadata page) as below, it does not show up in the dataset page: 
![capture](https://user-images.githubusercontent.com/6911487/39023185-265d281a-4407-11e8-8d66-8bcc6e43d99d.PNG)

![image](https://user-images.githubusercontent.com/6911487/39023250-82893160-4407-11e8-8d12-734fa6261e7d.png)

**Comment by jodiegardiner** [comment]
As the help box says, if you type  group:"MTF Survey" into the search box on the dataset list, then you get the expected behaviour.

![screen shot 2018-04-27 at 09 31 41](https://user-images.githubusercontent.com/21362845/39352845-e24aee8a-49fd-11e8-8157-81490fb6660b.png)

The group facet your screenshot shows is not connected with this feature at all.

**Comment by Naigege** [comment]
![image](https://user-images.githubusercontent.com/6911487/39382068-5b09257e-4a32-11e8-871a-c92a8af3de0f.png)

To create a group, use <energydata.info/group>

**Comment by shandaoz** [comment]
Following Naichen's instructions of creating a group from https://energydata.info/group , I did not see any options to add groups.
![groups shot](https://user-images.githubusercontent.com/36420556/45115317-80ed3f80-b11d-11e8-8701-cea8b2191331.png)

**Comment by jodiegardiner** [comment]
Works for me when I log in as you. Please check.
