### ISSUE TITLE
Shared links to Social Media have no thumbnails

### ISSUE THREAD

**Issue by jodiegardiner** [energy-data/energydata.info#238]
This is determined by a meta tag like so:

`<meta property="og:image" content="https://energydata.info/images/meta/default-meta-image.png" />`

This tag is present at the moment, so the image must be corrupted.

**Comment by shandaoz** [comment]
Hi Jodie, I am don't quite understand the phrase "the image must be corrupted". Do you mean because there is a meta tag in place, we can't add any images to it? 
When we share a dataset on social media, the shared link does not have any thumbnail image and doesn't look good. Is there a way for us to add thumbnail images or use one image for all social media links?

**Comment by jodiegardiner** [comment]
Sorry if I wasn't clear shandaoz.  I know how to fix this (the default image we use has become corrupted so it just needs replaced.) My comment above is just for documentation rather than a task for anyone else.

**Comment by shandaoz** [comment]
I see. Thanks for clearing that up Jodie!

**Comment by jodiegardiner** [comment]
As can be seen on the [facebook developer console](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fenergydata.info%2Fdataset%2Fcities-in-afghanistan), this is now working.  The .png file which had been in place before had become corrupted, so I have replaced the image. I also noticed the preview image for Twitter was missing in the same way and fixed that too.

Screenshot attached:

<img width="1017" alt="developer_console" src="https://user-images.githubusercontent.com/21362845/43223154-18597f22-904a-11e8-9a42-3ae535b600ba.png">

@JemiTheKey @TigranParvanyan
