### ISSUE TITLE
Harvester not working 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#273]
It seems that the ENERGYDATA harvester has stopped working. I merged 4 datasets into one dataset on DDH last Thursday (April 11), but these changes were not reflected on ENERGYDATA.[ I merged Pakistan - Biomass Industrial, Pakistan - Biomass Field Survey and Pakistan - Biomass Feedstock Crop Yield, into Pakistan - Biomass GIS Atlas](https://energydata.info/dataset?q=pakistan+biomass), which is now Pakistan – Biomass Mapping  on DDH.

**Comment by jodiegardiner** [comment]
Hi Shandao.

Does this new dataset have the correct tag that tells our harvester to get it?  The harvester is running like it should.

The tag in question is: 
[field_tags]=1437

**Comment by shandaoz** [comment]
Hi Jodie,

Strangely enough, the Pakistan – Biomass Mapping dataset on DDH is correctly tagged. 
![image](https://user-images.githubusercontent.com/36420556/56218020-39734e00-6032-11e9-9989-f3240ca12177.png)
For the other 3 datasets that were unpublished on DDH, the harvester should have removed them on ENERGYDATA, but it did not. 

Would this issue possibly be on DDH's side?

**Comment by jodiegardiner** [comment]
Hi Shandao, 

I've conducted a wee bit of an investigation on this one today and have identified and fixed the problem. The issue was in my script and a badly formatted date was breaking the importer for that dataset.

You can check here:
https://energydata.info/dataset/pakistan-biomass-mapping

If you're happy please close the ticket.

I should add that our harvester does not delete datasets. It's too dangerous to do so automatically as a small data entry error by a user could have big ramifications.  I would recommend manually deleting any datasets like this (there shouldn't be many, right?) or making them private will also hide them from public view but maintain a record of their existence.

**Comment by shandaoz** [comment]
Hi Jodie,

Thanks so much for looking into this! It's good to know that datasets will not be deleted. I will deactivate them instead. 

I will close this ticket, but on a side note,  ENERGYDATA has not been receiving updates for two weeks. Is this feature under development?
