### ISSUE TITLE
Establish API connection with a NRGI Dataset 

### ISSUE THREAD

**Issue by shandaoz** [energy-data/energydata.info#284]
[The EITI data](https://www.resourcedata.org/dataset/eiti-complete-summary-table) has regular updates at least a dozen times a year. NRGI requests to establish an automatic data feed via a CKAN formatted API from ResourceData.org to ENERGYDATA.

**Comment by jodiegardiner** [comment]
I have reached out to Tommy last week to ask which datasets he wishes to be harvested.  The infrastructure is in place.

**Comment by shandaoz** [comment]
The dataset NRGI wants to connect is [EITI Complete Summary Data Table](https://www.resourcedata.org/dataset/eiti-complete-summary-table)

**Comment by jodiegardiner** [comment]
Oh, fantastic, I'll get that sorted then.

**Comment by jodiegardiner** [comment]
This is done and can be viewed here;

https://energydata.info/dataset/eiti-complete-summary-table

There is a job running every night to update the dataset if there are changes. The dataset is updated about once a month on resourcedata.org but our job runs nightly so that there is only a short delay between update on the host and that being reflected on energydata.info.

Derilinx alerting NRGI to this update today.
