### ISSUE TITLE
editor cannot upload the dataset

### ISSUE THREAD

**Issue by hy347mc** [energy-data/energydata.info#287]
Editor of the Enerdata (a new organization) couldn't upload their datasets: each time after clicking on the "add data" button, they will get an empty white page. They are using Chrome.

**Comment by ss-bhat** [comment]
Fixed in the prod - 

This bug was related to Unicode in request headers - cors_origin_allowed = u'*'. Unicodes are not allowed in response headers. This was affecting below mentioned areas

- Creating a new user account.
- Adding a member to the organization.
- Adding a new dataset.

Please let me know if you face any further issues.

Thanks

**Comment by hy347mc** [comment]
> Fixed in the prod -
> 
> This bug was related to Unicode in request headers - cors_origin_allowed = u'*'. Unicodes are not allowed in response headers. This was affecting below mentioned areas
> 
> * Creating a new user account.
> * Adding a member to the organization.
> * Adding a new dataset.
> 
> Please let me know if you face any further issues.
> 
> Thanks

Hi there, thank you so much! Verified.
