### ISSUE TITLE
Organize the tags (countries, topics, etc.) by alphabetical order on facet list

### ISSUE THREAD

**Issue by jodiegardiner** [energy-data/energydata.info#304]
see title

**Comment by jodiegardiner** [comment]
@hy347mc 

Items within tags now listed alphabetically.  Check the left hand menu to see the change in effect here:
https://energydata.staging.derilinx.com/dataset

If satisfied, please comment here and I will push to prod and close the ticket.

Thank you.

**Comment by hy347mc** [comment]
> @hy347mc
> 
> Items within tags now listed alphabetically. Check the left hand menu to see the change in effect here:
> https://energydata.staging.derilinx.com/dataset
> 
> If satisfied, please comment here and I will push to prod and close the ticket.
> 
> Thank you.

Hi Jodie,

I cannot see this by clicking the link you shared with me. I got 502 Bad Gateway.

**Comment by jodiegardiner** [comment]
Hi @hy347mc,

That happens whilst the site is in the process of rebuilding (something I am doing quite often as I work on new features and test). If you see that, simply wait roughly 30 seconds and try again.

Thanks!

**Comment by hy347mc** [comment]
> Hi @hy347mc,
> 
> That happens whilst the site is in the process of rebuilding (something I am doing quite often as I work on new features and test). If you see that, simply wait roughly 30 seconds and try again.
> 
> Thanks!

Hi Jodie,

I can see it now and the tags are indeed displayed alphabetically; however, I did notice one thing that doesn't make sense to me and needs to be modified. Please see below. 

After clicking "show more organizations", the list of organizations will be extended correctly; however, the word displayed under all organizations is "only show popular organizations". But if we actually click that, we will go back to the organization names listed by alphabetical order not the popularity. 

I suggest that we stick with displaying the tags alphabetically, since we already have had the "order by" and the option "popular" on the top right. Hence, we might need to change the wording to "Show less organizations" or something else. What do you think?

![Capture2](https://user-images.githubusercontent.com/34387745/64975750-bb83cf00-d87d-11e9-84a3-1b1135af56ba.PNG)

**Comment by jodiegardiner** [comment]
Agree with your suggestion and implemented. Looks great!
