### ISSUE TITLE
Carry out final review and inspection for portal before launch

### ISSUE THREAD

**Issue by deirdrelee** [energy-data/energydata.info#335]
So we can go live immediately once we get green light from WB 
final testing and validation

**Comment by jodiegardiner** [comment]
Hi,

Please record feedback/issues with the final test phase here.  I was not able to replicate any of the issues encountered in the email.

I did address the changes requested, including moving the search box, altering font size in the search box and reordering navigation tabs so About comes first.

Thanks,

Please include links to affected pages and a screenshot of the issue if relevant.

Once you are 100% satisfied with the site, we can go live.

**Comment by hy347mc** [comment]
> Hi,
> 
> Please record feedback/issues with the final test phase here. I was not able to replicate any of the issues encountered in the email.
> 
> I did address the changes requested, including moving the search box, altering font size in the search box and reordering navigation tabs so About comes first.
> 
> Thanks,
> 
> Please include links to affected pages and a screenshot of the issue if relevant.
> 
> Once you are 100% satisfied with the site, we can go live.

- [x] Can we make this map fit in the screen. Currently, users have to scroll down to see the rest of the map. 
- [ ] When users open the website and go to this section, the map either blinks or turns into a whole light green screen before it shows. Is this the way it is supposed to be or it will not exist once we launch the website. 
<img width="1273" alt="Screen Shot 2020-02-04 at 12 08 36 PM" src="https://user-images.githubusercontent.com/34387745/73768559-3a06dd80-4747-11ea-9c64-ad2f4ebae620.png">

- [x] Can we make other elements on the homepage compactly so that we can see "Explore Data by Country" as well without scrolling down? People may not notice it without scrolling down. 
<img width="1280" alt="Screen Shot 2020-02-04 at 12 12 38 PM" src="https://user-images.githubusercontent.com/34387745/73769064-11331800-4748-11ea-92f2-e88dc73996da.png">

- [x] Partners on this page should be center-aligned.
<img width="1271" alt="Screen Shot 2020-02-04 at 12 26 07 PM" src="https://user-images.githubusercontent.com/34387745/73770188-f95c9380-4749-11ea-92ab-c61cd13610c9.png">

- [x] These are what the main page look like on mobile. The icons are not visible, so does the world map for exploring by country. Each section is right next to each other without boundaries, need to figure out another way to display the home page for mobile users. 
<img width="267" alt="Screen Shot 2020-02-04 at 12 30 48 PM" src="https://user-images.githubusercontent.com/34387745/73770586-a0d9c600-474a-11ea-99bb-14e3249bfcaa.png">
<img width="267" alt="Screen Shot 2020-02-04 at 12 30 59 PM" src="https://user-images.githubusercontent.com/34387745/73770593-a46d4d00-474a-11ea-93fa-84958fb22b5f.png">

- [ ] This is what the dataset page looks like on mobile. The search icon (the magnifying glass) is moved to the next line, hence it needs to be moved back after the search box but on the same line. 
<img width="265" alt="Screen Shot 2020-02-04 at 12 31 07 PM" src="https://user-images.githubusercontent.com/34387745/73770767-fe6e1280-474a-11ea-94e3-e7f957cec6e1.png">

**There are two issues with the logic of the filter on the Dataset page:** 
- [ ] The way we are currently arranging the options under each filter is by alphabetical order, not the popularity order. Hence, after I expand click on "show more countries" for example; the clickable thing at the bottom under this filter should be "show fewer countries" not "Show only popular countries". Because again, we are following the alphabetical order, not the popularity order. Please keep the consistency. 
<img width="1268" alt="Screen Shot 2020-02-04 at 12 47 36 PM" src="https://user-images.githubusercontent.com/34387745/73771562-98828a80-474c-11ea-8c34-f949aefb4436.png">

- [ ] When adding the several options **within the same filter** (for example, if I want to see all datasets on Angola and Egypt), the server should display the **sum** not the **intersection** of the datasets. See the example below, I want to see datasets on Angola and Egypt, the **total amount of the datasets displayed should = the number of datasets on Angola + the number of datasets on Egypt - the number of intersected datasets between these two countries**. 

However, when adding on the options **across different filters**, the server should follow those filters and options strictly, and display only the datasets that satisfy all options across different filters. In this case, the current website works correctly. 

<img width="1280" alt="Screen Shot 2020-02-04 at 12 48 30 PM" src="https://user-images.githubusercontent.com/34387745/73772092-8a813980-474d-11ea-978e-956c549071d3.png">
<img width="1279" alt="Screen Shot 2020-02-04 at 12 48 59 PM" src="https://user-images.githubusercontent.com/34387745/73772098-8e14c080-474d-11ea-950f-9d5486571988.png">

**Comment by jodiegardiner** [comment]
Hi @hy347mc ,

Just wanted to give you an update on the work I've done from your feedback above and make sure we're looking at the same build. I'll also make comments where appropriate as points we can discuss further on the call.

Site looks great on all mobile devices. The map is a bit too large (or becomes too tiny) when included on a smartphone screen in portrait mode but if you rotate the device, that's enough space for the map to fit. I could not find any device where the dataset page looked messy like you found.

The category icons looked a little cluttered on the smartphone portrait screen, so those are hidden at anything below a tablet. We could have a panel dedicated to them the same as we do for the app and the carousel.

Partners page looks great now with aligned columns.

It greatly depends which size of screen you are viewing the site on as to whether you see the arrow pointing to the map. It's tricky to fit what we have above the line in as it is. Narrowing it further would be tricky.

For the filtering issue, that will require a bit more effort to resolve so could we perhaps consider this as a post-launch priority instead?

**Comment by hy347mc** [comment]
> Hi @hy347mc ,
> 
> Just wanted to give you an update on the work I've done from your feedback above and make sure we're looking at the same build. I'll also make comments where appropriate as points we can discuss further on the call.
> 
> Site looks great on all mobile devices. The map is a bit too large (or becomes too tiny) when included on a smartphone screen in portrait mode but if you rotate the device, that's enough space for the map to fit. I could not find any device where the dataset page looked messy like you found.
> 
> The category icons looked a little cluttered on the smartphone portrait screen, so those are hidden at anything below a tablet. We could have a panel dedicated to them the same as we do for the app and the carousel.
> 
> Partners page looks great now with aligned columns.
> 
> It greatly depends which size of screen you are viewing the site on as to whether you see the arrow pointing to the map. It's tricky to fit what we have above the line in as it is. Narrowing it further would be tricky.
> 
> For the filtering issue, that will require a bit more effort to resolve so could we perhaps consider this as a post-launch priority instead?

Great, let's get back to the filter part after launching it next Monday, Feb 10th; otherwise, looks good w/ me! Thanks Jodie.

**Comment by jodiegardiner** [comment]
These issues are addressed with the exception of the post launch filtering piece. Creating a new issue for that now.
