### ISSUE TITLE
Federate open data site

### ISSUE THREAD

**Issue by olafveerman** [energy-data/energydata.info#35]
Datasets from: http://data.energy-gis.opendata.arcgis.com/ will be pulled into Energy Data.

**Comment by kamicut** [comment]
@olafveerman I have started work on this. Here's a couple of questions from my tests:

- The datasets need to be pulled into an organization, do I use an existing organization or do I create a new one for the ArcGIS data?
- What is the frequency that we need to poll the ArcGIS server? We can do daily, weekly, monthly

Furthermore, one UX problem when federating is that the GeoJSON resources pulled down from the federated site do not display in energydata.info because GeoJSON is set to read from our MVT extension. Should we have an alternative GeoJSON view for these resources?

**Comment by olafveerman** [comment]
Pulling in @yanntanvez to answer the two questions.

Let's open another issue for the GeoJSON preview.

**Comment by kamicut** [comment]
This is deployed, @olafveerman should we close this?
