### ISSUE TITLE
EDI Mobility Usability Issues

### ISSUE THREAD

**Issue by gclapp1** [energy-data/energydata.info#370]
Follow up to Google Alert sent to Oliver Knight:

_"Search Console has identified that your site is affected by 1 Mobile Usability issue(s). The following issues were found on your site. We recommend that you fix these issues when possible to enable the best experience and coverage in Google Search."_

**Comment by jodiegardiner** [comment]
Hi @gclapp1 ,

I looked at the Search Console report in detail and 49 pages out of 2098 scanned had one of three issues.

I've updated so that the page titles don't extend beyond the edges of the screen now, which was one of them.

The others are:
Text too small to read. On smaller screens I bumped the text size up.
Items too close together. I buffed a few margins.
