### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by minjaegal** [energy-data/energydata.info#391]
1.Dashboard - Pending Datasets shows Internal Server Error
![제목 없음](https://github.com/energy-data/energydata.info/assets/132272564/53b0d640-0a27-4e34-a328-c77c5b25d278)
2.Internal Server Error shows when clicking the datasets
![gep](https://github.com/energy-data/energydata.info/assets/132272564/a7d53519-b7a9-4b69-a96a-a2e81eff094e)

**Comment by anderspeders** [comment]
Tagging @jodiegardiner for your review and action

**Comment by jodiegardiner** [comment]
HI @anderspeders 

We live patched the server error yesterday and have been monitoring our error logs since. In the ~20 hours or so it has been since then we have not seen any further server errors reported to the log.

I have created a new ticket for the Resource Upload issue #392 which is now also resolved.
