### ISSUE TITLE
Federate OpenEI

### ISSUE THREAD

**Issue by olafveerman** [energy-data/energydata.info#50]
Selective federation of [Open EI](http://en.openei.org/), potentially all the non US datasets.

- investigate technical possibilities to selectively federate (@kamicut)
- determine what datasets to sync, or what criteria to use. (@yanntanvez)

**Comment by kamicut** [comment]
As an update here, I've looked at the code in [ckanext-harvest](https://github.com/ckan/ckanext-harvest), the plugin we use for harvesting. There is an option for harvesting on a per CKAN organization basis which we could use.

That might not be sufficient for all criteria, and we might have to fork and modify the harvester to extend the organization filter (extending [this PR](https://github.com/ckan/ckanext-harvest/pull/158)). The way this works is that the harvester calls `package_search` with a list of filters and harvests only the datasets that are returned. We will need some time exploring the code to determine feasibility and time requirements. 

As an alternative, if @yanntanvez's criteria can't be mapped to a `package_search` query we will need to write another plugin. @olafveerman I think this is also necessary when we were talking about "cloning" the resources locally rather than harvesting the metadata.

**Comment by olafveerman** [comment]
A set of curated Open EI datasets will be incorporated manually. Closing this issue.
