### ISSUE TITLE
Country list

### ISSUE THREAD

**Issue by yanntanvez** [energy-data/energydata.info#6]
Hi there,

Country list with 3 letters is sub-optimal compared to previous list with full country names.

Nigeria was not part of the list.

Best,
-Yann

**Comment by olafveerman** [comment]
The previous country tags were giving errors when adding multiple countries, which is why we started an alternative implementation. The three letter code is not optimal and we'll work on a fix to translate them into the full names toward the user.

In the meantime you can keep tagging. The future fix should automatically update the tags that are currently in the system.
The iso code for Nigeria is `nga` btw

**Comment by yanntanvez** [comment]
Let's please keep this issue in my mind with objective to have the full country list available shortly. Thanks!

**Comment by kamicut** [comment]
Closed with #44
